services:
  vscgallery:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-80}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - letsencrypt-certs:/certs
    networks:
      - letsencrypt-network

volumes:
  letsencrypt-certs:
    external: true

networks:
  letsencrypt-network:
    external: true